# Generated by Django 5.2 on 2025-04-24 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='tiile',
            new_name='title',
        ),
    ]
